name: charts_common
version: 0.12.0
description: A common library for charting packages.
homepage: https://github.com/google/charts

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  collection: ^1.19.1
  intl: ^0.20.1
  logging: ^1.3.0
  meta: ^1.16.0
  vector_math: ^2.1.4

dev_dependencies:
  mockito: ^5.4.4
  test: ^1.25.12

dependency_overrides:
  collection: ^1.19.1
  test_api: ^0.7.4
  meta: ^1.16.0
  intl: ^0.20.1
